# Generated by Django 4.2.6 on 2024-05-18 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=6)),
                ('image_search_label', models.CharField(max_length=255)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fashion_style', models.CharField(max_length=255)),
                ('fashion_brand', models.CharField(max_length=255)),
                ('cloth_type', models.CharField(max_length=255)),
                ('garment_fitting', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img_url', models.URLField(blank=True)),
            ],
        ),
    ]
