# Generated by Django 4.2.6 on 2024-05-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="img",
        ),
        migrations.AddField(
            model_name="product",
            name="img_url",
            field=models.URLField(blank=True),
        ),
    ]
