# Generated by Django 4.2.6 on 2024-05-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
